[package]
name = "dicer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
peg = "0.8.5"
wasm-bindgen = "0.2.100"

[dev-dependencies]
proptest = "1.7.0"
proptest-derive = "0.6.0"
